### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by KagamiChan** [KagamiChan/kcsapi.ts#1]
1. [x] discover a typing generator for kcsapi json files: `quicktype`
1. [x] prototype on how the generator work
1. [x] define how to anonymize data samples
1. [x] scripts to anonymize
1. [x] create sample set
1. [x] define how to store typings
1. [x] generate typings from sample set
1. [x] more samples
1. [x] initial publish
